/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cena;

import javax.swing.ImageIcon;

/**
 *
 * @author quiqu
 */
public class interfaz extends javax.swing.JFrame {

    /**
     * Creates new form interfaz
     */
    public interfaz() {
        initComponents();
        
        gifFilosofo1.setIcon(new ImageIcon(getClass().getResource("/imagenes/pensando.gif")));
        gifFilosofo2.setIcon(new ImageIcon(getClass().getResource("/imagenes/pensando.gif")));
        gifFilosofo3.setIcon(new ImageIcon(getClass().getResource("/imagenes/pensando.gif")));
        gifFilosofo4.setIcon(new ImageIcon(getClass().getResource("/imagenes/pensando.gif")));
        gifFilosofo5.setIcon(new ImageIcon(getClass().getResource("/imagenes/pensando.gif")));
        
        semaforo5.setIcon(new ImageIcon(getClass().getResource("/imagenes/semaforoVerde.png")));
        semaforo1.setIcon(new ImageIcon(getClass().getResource("/imagenes/semaforoVerde.png")));
        semaforo2.setIcon(new ImageIcon(getClass().getResource("/imagenes/semaforoVerde.png")));
        semaforo3.setIcon(new ImageIcon(getClass().getResource("/imagenes/semaforoVerde.png")));
        semaforo4.setIcon(new ImageIcon(getClass().getResource("/imagenes/semaforoVerde.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Background = new javax.swing.JPanel();
        semaforo5 = new javax.swing.JLabel();
        semaforo4 = new javax.swing.JLabel();
        semaforo3 = new javax.swing.JLabel();
        semaforo2 = new javax.swing.JLabel();
        semaforo1 = new javax.swing.JLabel();
        numeroFilosofo5 = new javax.swing.JLabel();
        numeroFilosofo4 = new javax.swing.JLabel();
        numeroFilosofo3 = new javax.swing.JLabel();
        numeroFilosofo2 = new javax.swing.JLabel();
        numeroFilosofo1 = new javax.swing.JLabel();
        gifFilosofo5 = new javax.swing.JLabel();
        gifFilosofo4 = new javax.swing.JLabel();
        gifFilosofo3 = new javax.swing.JLabel();
        gifFilosofo2 = new javax.swing.JLabel();
        gifFilosofo1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Nombre1 = new javax.swing.JLabel();
        Nombre2 = new javax.swing.JLabel();
        Nombre3 = new javax.swing.JLabel();
        Nombre4 = new javax.swing.JLabel();
        Nombre5 = new javax.swing.JLabel();
        Conteo1 = new javax.swing.JLabel();
        Conteo2 = new javax.swing.JLabel();
        Conteo3 = new javax.swing.JLabel();
        Conteo4 = new javax.swing.JLabel();
        Conteo5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Mesa = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        reporteSalida = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setToolTipText("");
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Background.add(semaforo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 20, 20));
        Background.add(semaforo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, 20, 20));
        Background.add(semaforo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 20, 20));
        Background.add(semaforo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 20, 20));
        Background.add(semaforo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 20, 20));

        numeroFilosofo5.setText("5");
        Background.add(numeroFilosofo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        numeroFilosofo4.setText("4");
        Background.add(numeroFilosofo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, -1, -1));

        numeroFilosofo3.setText("3");
        Background.add(numeroFilosofo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        numeroFilosofo2.setText("2");
        Background.add(numeroFilosofo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, -1, -1));

        numeroFilosofo1.setText("1");
        Background.add(numeroFilosofo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));
        Background.add(gifFilosofo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 60, 60));
        Background.add(gifFilosofo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, 60, 60));
        Background.add(gifFilosofo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 60, 60));
        Background.add(gifFilosofo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 270, 60, 60));
        Background.add(gifFilosofo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 60, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/uvm.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Black", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 51));
        jLabel2.setText("La Cena de los Filósofos");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Creado por: José Enrique Rojas Macedo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(27, 27, 27))
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 740, 130));

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("INICIAR PROCESO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 419, 170, 49));

        jPanel3.setBackground(new java.awt.Color(0, 0, 102));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombre1.setForeground(new java.awt.Color(255, 255, 255));
        Nombre1.setText("Filosofo 1:");
        jPanel3.add(Nombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        Nombre2.setForeground(new java.awt.Color(255, 255, 255));
        Nombre2.setText("Filosofo 2:");
        jPanel3.add(Nombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        Nombre3.setForeground(new java.awt.Color(255, 255, 255));
        Nombre3.setText("Filosofo 3:");
        jPanel3.add(Nombre3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        Nombre4.setForeground(new java.awt.Color(255, 255, 255));
        Nombre4.setText("Filosofo 4:");
        jPanel3.add(Nombre4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        Nombre5.setForeground(new java.awt.Color(255, 255, 255));
        Nombre5.setText("Filosofo 5:");
        jPanel3.add(Nombre5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, -1, -1));

        Conteo1.setForeground(new java.awt.Color(255, 255, 255));
        Conteo1.setText("0");
        jPanel3.add(Conteo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        Conteo2.setForeground(new java.awt.Color(255, 255, 255));
        Conteo2.setText("0");
        jPanel3.add(Conteo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        Conteo3.setForeground(new java.awt.Color(255, 255, 255));
        Conteo3.setText("0");
        jPanel3.add(Conteo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        Conteo4.setForeground(new java.awt.Color(255, 255, 255));
        Conteo4.setText("0");
        jPanel3.add(Conteo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, -1, -1));

        Conteo5.setForeground(new java.awt.Color(255, 255, 255));
        Conteo5.setText("0");
        jPanel3.add(Conteo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 269, 230, 118));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 270));

        Background.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 500));

        Mesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/filosofos.png"))); // NOI18N
        Background.add(Mesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 310, 310));

        jLabel5.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel5.setText("Visualización:");
        Background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        reporteSalida.setColumns(20);
        reporteSalida.setRows(5);
        jScrollPane1.setViewportView(reporteSalida);

        Background.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 370, 300));

        jLabel6.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel6.setText("Log:");
        Background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
       palillo palillo1 = new palillo();
       palillo palillo2 = new palillo();
       palillo palillo3 = new palillo();
       palillo palillo4 = new palillo();
       palillo palillo5 = new palillo();
       
       filosofoIzquierdo f1 = new filosofoIzquierdo(palillo2, palillo1, 1, gifFilosofo1, reporteSalida, semaforo1, semaforo5, Conteo1);
       filosofoDerecho f2 = new filosofoDerecho(palillo3, palillo2, 2, gifFilosofo2, reporteSalida, semaforo2, semaforo1, Conteo2);
       filosofoIzquierdo f3 = new filosofoIzquierdo(palillo4, palillo3, 3, gifFilosofo3, reporteSalida, semaforo3, semaforo2, Conteo3);
       filosofoDerecho f4 = new filosofoDerecho(palillo5, palillo4, 4, gifFilosofo4, reporteSalida, semaforo4, semaforo3, Conteo4);
       filosofoIzquierdo f5 = new filosofoIzquierdo(palillo1, palillo5, 5, gifFilosofo5, reporteSalida, semaforo5, semaforo4, Conteo5);
       
       f1.start();
       f2.start();
       f3.start();
       f4.start();
       f5.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Conteo1;
    private javax.swing.JLabel Conteo2;
    private javax.swing.JLabel Conteo3;
    private javax.swing.JLabel Conteo4;
    private javax.swing.JLabel Conteo5;
    private javax.swing.JLabel Mesa;
    private javax.swing.JLabel Nombre1;
    private javax.swing.JLabel Nombre2;
    private javax.swing.JLabel Nombre3;
    private javax.swing.JLabel Nombre4;
    private javax.swing.JLabel Nombre5;
    private javax.swing.JLabel gifFilosofo1;
    private javax.swing.JLabel gifFilosofo2;
    private javax.swing.JLabel gifFilosofo3;
    private javax.swing.JLabel gifFilosofo4;
    private javax.swing.JLabel gifFilosofo5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel numeroFilosofo1;
    private javax.swing.JLabel numeroFilosofo2;
    private javax.swing.JLabel numeroFilosofo3;
    private javax.swing.JLabel numeroFilosofo4;
    private javax.swing.JLabel numeroFilosofo5;
    private javax.swing.JTextArea reporteSalida;
    private javax.swing.JLabel semaforo1;
    private javax.swing.JLabel semaforo2;
    private javax.swing.JLabel semaforo3;
    private javax.swing.JLabel semaforo4;
    private javax.swing.JLabel semaforo5;
    // End of variables declaration//GEN-END:variables
}
